const Map<String, String> ar = {
  'Login': 'تسجيل الدخول',
  'Email': 'البريد الالكتروني',
  'Password': 'الرقم السري',
  'Forget Your Password ?': 'هل نسيت الرقم السري؟',
  'Does not Have an Account?': 'هل تمتلك حساب بالفعل؟',
  'SignUp': 'انشاء حساب جديد  ',
  'Home Page': 'الصفحه الرئيسيه',
  'About Us': 'معلومات عنا',
  'Courses': 'الدورات',
  'Chief Team': 'طاقم العمل',
  'Contact Us': 'تواصل معنا',
  'Log Out': 'تسجيل خروج',
  'Country': 'البلد',
  'Live': 'بث مباشر',
  'Playlist': 'قائمة التشغيل',
  'Profile': 'الصفحه الشخصيه',
  'First Name': 'الاسم الاول',
  'Last Name': 'الاسم الاخير',
  'Gender': 'الجنس',
  'Phone Number': 'رقم الموبايل',
  'Choose Your Country': 'اختر بلدك',
  'Confirm Password': 'تاكيد الرقم السري',
  'Already Have an Account?': 'هل لديك حساب؟',
  'What is Chef Khalil School?': 'ما هي مدرسة الشيف خليل؟',
  'We are an enthusiastic team made up of world-class culinary teachers and former executives of culinary schools.':
      'نحن فريق متحمس يتكون من مدرسين طهي على مستوى عالمي ومديرين تنفيذيين سابقين في مدارس الطهي.',
  'Fill up the information below if there is a problem to contact with our team':
      'املأ المعلومات أدناه إذا كانت هناك مشكلة يرجي الاتصال بفريقنا',
  'Full Name': 'الاسم بالكامل',
  'Subject': 'الموضوع',
  'Message.....': 'الرساله',
  'Send': 'ارسال',
  'Follow with us all new': 'تابع معنا كل جديد',
  'Our Cooking Classes': 'أحدث دورس الطبخ',
  'View More Classes': 'عرض المزيد من الفئات',
  'Our team of professionals': 'فريقنا من المحترفين',
  'Best Chefs of Chef’s Khalil School': 'افضل الشيفات في مدرسة الشيف خليل',
  'Latest news From Chef Khalil School': 'آخر الأخبار من مدرسة الشيف خليل',
  'Our Recent Blog Posts': 'مشاركات المدونة الأخيرة لدينا',
  '© all rights reserved to chef khalil school':
      '© جميع الحقوق محفوظة لمنصة الشيف خليل',
  'View Profile': 'عرض الصفحة الشخصية',
  'All Courses': 'جميع الدورات',
  'Course Details': 'تفاصيل الدوره',
  'Show Course': 'عرض الدوره',
  'Enroll': 'تسجيل',
  'Description': 'التفاصيل',
  'Course Content': 'محتوي الدوره',
  'Lessons  List  -': 'قائمة الدروس -',
  'Total': 'مجموع',
  'Share On Social Media': 'شارك على وسائل التواصل الاجتماعي',
  'Enroll To Continue Watching...': 'سجل لمتابعة المشاهدة ...',
  'All Chiefs': 'كل الفريق',
  '*this field is required': '*هذه الخانة مطلوبه',
  'password must at least 6 characters': 'يجب أن لا تقل كلمة المرور عن 6 أحرف',
  'Forget Password': ' نسيت كلمة السر',
  'Edit Profile': 'تعديل الملف الشخصي',
  'Together we discover what makes the recipes work, and share what we are learning to help everyone cook with confidence.':
      'نكتشف معًا ما الذي يجعل الوصفات تعمل ، ونشارك ما نتعلمه لمساعدة الجميع على الطهي بثقة.',
  'We test cookware and ingredients to find the best quality dishes and recipes for all students.':
      'نقوم باختبار أدوات الطهي والمكونات للعثور على أفضل الأطباق والوصفات عالية الجودة لجميع الطلاب.',
  'We rely on an exceptional group of international employees and chefs.':
      'نعتمد على مجموعة استثنائية من الموظفين والطهاة الدوليين.',
  'We have a group of chefs and staff who bring a wealth of skills, ideas, personal experiences and multicultural perspectives.':
      'لدينا مجموعة من الطهاة والموظفين الذين يجلبون ثروة من المهارات والأفكار والتجارب الشخصية ووجهات النظر متعددة الثقافات.',
  'Use of the highest cooking standards': 'استخدام أعلى معايير الطهي',
  'We are always keen to use the highest international standards and focus on basic techniques while developing course curricula that provide students with complete information to master the correct technique for the recipe in addition to that students receive constant instructions and support from the chef.':
      'نحن حريصون دائمًا على استخدام أعلى المعايير الدولية والتركيز على التقنيات الأساسية أثناء تطوير مناهج الدورة التدريبية التي تزود الطلاب بمعلومات كاملة لإتقان التقنية الصحيحة للوصفة بالإضافة إلى تلقي الطلاب التعليمات والدعم المستمر من الشيف.',
  'Trained by professional chefs': 'تدرب على يد طهاة محترفين',
  'We are a team made up of world-class chef teachers and former executives of culinary schools dedicated to teaching cooking techniques to our students across the Arab world - completely online. Additionally, we offer traditional or vegetarian content preferences.':
      'نحن فريق مكون من مدرسين طهاة من الطراز العالمي ومديرين تنفيذيين سابقين في مدارس الطهي مكرسة لتعليم تقنيات الطهي لطلابنا في جميع أنحاء العالم العربي - عبر الإنترنت بالكامل. بالإضافة إلى ذلك ، نحن نقدم تفضيلات المحتوى التقليدي أو النباتي.',
  'Enhance your cooking skills for life': 'عزز مهاراتك في الطهي مدى الحياة',
  'Gain confidence in your cooking abilities and become a professional chef, learn how to make different dishes easily for life. Learn to cook in the comfort of your home, participate in the professional cooking course offered by the School of Chef Khalil, enhance your abilities and have more confidence every time you apply a new recipe, learn professional cooking methods and secrets that make you a skilled chef.':
      'اكتسب الثقة في قدراتك في الطهي وكن طاهياً محترفًا ، وتعلم كيفية إعداد أطباق مختلفة بسهولة مدى الحياة. تعلم الطبخ براحة في منزلك ، شارك في دورة الطهي الاحترافية التي تقدمها مدرسة الشيف خليل ، وعزز قدراتك واكتسب المزيد من الثقة في كل مرة تقوم فيها بتطبيق وصفة جديدة ، وتعلم أساليب الطبخ الاحترافية والأسرار التي تجعلك ماهرًا طاه.',
  'View His Courses': 'عرض دوراته',
  'Send Message': 'أرسل رسالة',
  'Change Password': 'تغيير كلمة المرور',
  'Quiz name :': 'اسم الاختبار:',
  'Quiz Description :': 'وصف الاختبار:',
  'Number Of questions:': 'عدد الأسئلة:',
  'Total score:': 'مجموع النقاط:',
  'We play food with fire strings': 'نلعب الطعام بخيوط النار',
  'Watch Our Next Live In': 'شاهد التالي مباشرة في',
  '33      34      23      29': '33      34      23      29',
  'Seconds': 'ثواني',
  'Minutes': 'دقائق',
  'Hours': 'ساعات',
  'Days': 'أيام',
  'Watch Soon': 'شاهد قريبًا',
  'male': 'ذكر',
  'female': 'انثي',
  'Syrian Arab Republic': 'سوريا',
  'Egypt': 'مصر',
  'Edit Profile Details': 'تعديل البيانات الشخصيه',
  'Profile Image': 'الصوره الشخصيه',
  'Save Changes': 'حفظ التغيرات',
  'Current Password': 'كلمة المرور الحاليه',
  'New Password': 'كلمة المرور الجديده',
  'Confirm New Password': 'تاكيد كلمة المرور الجديده',
  'Advertisements': 'اعلانات',
  'Student': 'طالب',
  'All Live Stream':'كل البث المباشر',
  'Today':'اليوم',
  'Finished':'المنتهيه',
  'Coming':'القادمه'
};
