const Map<String, String> en = {
  'Login': 'Login',
  'Email': 'Email',
  'Password': 'Password',
  'Forget Your Password ?': 'Forget Your Password',
  'Does not Have an Account?': 'does not have an account?',
  'SignUp': 'SignUp ',
  'Home Page': 'Home page',
  'About Us': 'About Us',
  'Course': 'Courses',
  'Chief Team': 'Chief Team',
  'Contact Us': 'Contact Us',
  'Log Out': 'Log Out',
  'Live': 'Live',
  'Profile': 'Profile',
  'First Name': 'First Name',
  'Last Name': 'Last Name',
  'Gender': 'Gender',
  'Phone Number': 'Phone Number',
  'Choose Your Country': 'Choose Your Country',
  'Confirm Password': 'Confirm Password',
  'Already Have an Account?': 'Already Have an Account?',
  'What is Chef Khalil School?': 'What is Chef Khalil School?',
  'We are an enthusiastic team made up of world-class culinary teachers and former executives of culinary schools.':
      'We are an enthusiastic team made up of world-class culinary teachers and former executives of culinary schools.',
  'Fill up the information below if there is a problem to contact with our team':
      'Fill up the information below if there is a problem to contact with our team',
  'Full Name': 'Full Name',
  'Subject': 'Subject',
  'Message.....': 'Message.....',
  'Send': 'Send',
  'Follow with us all new': 'Follow with us all new',
  'Our Cooking Classes': 'Our Cooking Classes',
  'View More Classes': 'View More Classes',
  'Our team of professionals': 'Our team of professionals',
  'Best Chefs of Chef’s Khalil School': 'Best Chefs of Chef’s Khalil School',
  'Latest news From Chef Khalil School': 'Latest news From Chef Khalil School',
  'Our Recent Blog Posts': 'Our Recent Blog Posts',
  '© all rights reserved to chef khalil school':
      '© all rights reserved to chef khalil school',
  'View Profile': 'View Profile',
  'All Courses': 'All Courses',
  'Course Details': 'Course Details',
  'Show Course': 'Show Course',
  'Enroll': 'Enroll',
  'Description': 'Description',
  'Course Content': 'Course Content',
  'Lessons  List  -': 'Lessons  List  -',
  'Playlist': 'Playlist',
  'Total': 'Total',
  'Share On Social Media': 'Share On Social Media',
  'Enroll To Continue Watching...': 'Enroll To Continue Watching...',
  'All Chiefs': 'All Chiefs',
  '*this field is required': '*this field is required',
  'password must at least 6 characters': 'password must at least 6 characters',
  'Forget Password': 'Forget Password',
  'Edit Profile': 'Edit Profile',
  'Together we discover what makes the recipes work, and share what we are learning to help everyone cook with confidence.':
      'Together we discover what makes the recipes work, and share what we are learning to help everyone cook with confidence.',
  'We test cookware and ingredients to find the best quality dishes and recipes for all students.':
      'We test cookware and ingredients to find the best quality dishes and recipes for all students.',
  'We rely on an exceptional group of international employees and chefs.':
      'We rely on an exceptional group of international employees and chefs.',
  'We have a group of chefs and staff who bring a wealth of skills, ideas, personal experiences and multicultural perspectives.':
      'We have a group of chefs and staff who bring a wealth of skills, ideas, personal experiences and multicultural perspectives.',
  'Use of the highest cooking standards':
      'Use of the highest cooking standards',
  'We are always keen to use the highest international standards and focus on basic techniques while developing course curricula that provide students with complete information to master the correct technique for the recipe in addition to that students receive constant instructions and support from the chef.':
      'We are always keen to use the highest international standards and focus on basic techniques while developing course curricula that provide students with complete information to master the correct technique for the recipe in addition to that students receive constant instructions and support from the chef.',
  'Trained by professional chefs': 'Trained by professional chefs',
  'We are a team made up of world-class chef teachers and former executives of culinary schools dedicated to teaching cooking techniques to our students across the Arab world - completely online. Additionally, we offer traditional or vegetarian content preferences.':
      'We are a team made up of world-class chef teachers and former executives of culinary schools dedicated to teaching cooking techniques to our students across the Arab world - completely online. Additionally, we offer traditional or vegetarian content preferences.',
  'Enhance your cooking skills for life':
      'Enhance your cooking skills for life',
  'Gain confidence in your cooking abilities and become a professional chef, learn how to make different dishes easily for life. Learn to cook in the comfort of your home, participate in the professional cooking course offered by the School of Chef Khalil, enhance your abilities and have more confidence every time you apply a new recipe, learn professional cooking methods and secrets that make you a skilled chef.':
      'Gain confidence in your cooking abilities and become a professional chef, learn how to make different dishes easily for life. Learn to cook in the comfort of your home, participate in the professional cooking course offered by the School of Chef Khalil, enhance your abilities and have more confidence every time you apply a new recipe, learn professional cooking methods and secrets that make you a skilled chef.',
  'View His Courses': 'View His Courses',
  'Send Message': 'Send Message',
  'Change Password': 'Change Password',
  'Country': 'Country',
  'Quiz name :': 'Quiz name :',
  'Quiz Description :': 'Quiz Description :',
  'Number Of questions:': 'Number Of questions:',
  'Total score:': 'Total score:',
  'We play food with fire strings': 'We play food with fire strings',
  'Watch Our Next Live In': 'Watch Our Next Live In',
  '33      34      23      29': '33      34      23      29',
  'Seconds': 'Seconds',
  'Minutes': 'Minutes',
  'Hours': 'Hours',
  'Days': 'Days',
  'Watch Soon': 'Watch Soon',
  'male': 'male',
  'female': 'female',
  'Egypt': 'Egypt',
  'Syrian Arab Republic': 'Syrian Arab Republic',
  'Edit Profile Details': 'Edit Profile Details',
  'Profile Image': 'Profile Image',
  'Save Changes': 'Save Changes',
  'Current Password': 'Current Password',
  'New Password': 'New Password',
  'Confirm New Password': 'Confirm New Password',
  'Advertisement': 'Advertisement',
  'Student': 'Student',
  'All Live Stream':'All Live Stream',
  'Today':'Today',
  'Finished':'Finished',
  'Coming':'Coming'
};
